### ISSUE TITLE
支持 getUrl 方法，解决阿里云 isCName 和 CDN 冲突的问题

### ISSUE THREAD

**Issue by shaunthegeek** [xxtime/flysystem-aliyun-oss#1]
阿里云oss 支持 自定义域名，但如果设置了CDN，则会报错。比如：

https://github.com/jacobcyl/Aliyun-oss-storage/issues/26
https://github.com/jacobcyl/Aliyun-oss-storage/issues/30
https://github.com/jacobcyl/Aliyun-oss-storage/issues/36
https://github.com/jacobcyl/Aliyun-oss-storage/issues/41

解决办法：

https://github.com/jacobcyl/Aliyun-oss-storage/issues/32

**Comment by JoeByte** [comment]
这个问题稍后会解决，谢谢反馈

**Comment by lepig** [comment]
我也遇到这个问题了。配置`isCName`为true后，报错了。希望有时间能帮修复下，谢谢了。

**Comment by JoeByte** [comment]
```php
// 适合CDN与非CDN模式
$filesystem = new Filesystem(new OssAdapter([
    'accessId'     => '<access id>',
    'accessSecret' => '<access secret>',
    'bucket'       => '<bucket name>',
    'endpoint'     => 'oss-cn-hangzhou.aliyuncs.com', // 官方region
    'isCName'      => false,
]));

// 适合非CDN模式
$filesystem = new Filesystem(new OssAdapter([
    'accessId'     => '<access id>',
    'accessSecret' => '<access secret>',
    'bucket'       => '<bucket name>',
    'endpoint'     => 'img.xxtime.com',  // 自定义域名
    'isCName'      => true,
]));
```
这样用先

**Comment by ziyeziye** [comment]
修复了getUrl文件不存在报错的问题，和使用自定义域名(cdn)上传报错的问题:
https://github.com/ziyeziye/Aliyun-oss-storage
